---
title: "Alluvium Plot"
author: "Wu Gong"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: false
    code_folding: hide
    toc_depth: 6
    lightbox: true
    gallery: false
    highlight: monochrome
    css: Wu.css
---


	
```{r setup, echo=FALSE, cache=FALSE,warning=FALSE,message=FALSE}
library(knitr)
library(rmdformats)
library(Wu)
opts_chunk$set(echo=TRUE
             , cache=FALSE
             , eval=TRUE
             , prompt=FALSE
             , results="asis"
             , tidy=FALSE
             , comment=NA
             , message=FALSE
             , warning=FALSE
             , out.width = '80%'
             , class.source='klippy'
               )
eval_fast <- TRUE
eval_slow <- FALSE
klippy::klippy(position = c('top', 'left')
             , tooltip_message = 'Click to copy'
             , tooltip_success = 'Done')
```




# [Back to Index](index.html)



# Alluvium Plot with ggplot2

 * Use [ggplot2](https://cran.r-project.org/web/packages/ggplot2/index.html) and [ggalluvial](https://cran.r-project.org/web/packages/ggalluvial/index.html) package, plus [ggrepel](https://cran.r-project.org/web/packages/ggrepel/index.html) package
 
 ```{r}
 library(data.table)
 library(ggplot2)
 library(ggalluvial)
 library(ggrepel)
 dt <- data.table(
     id = 1:150
   , col1 = factor(sample(c("I", "II"), size = 150, replace = TRUE, prob = c(0.4, 0.6)))
   , col2 = factor(sample(c("A", "B"), size = 150, replace = TRUE, prob = c(0.3, 0.7)))
   , col3 = factor(sample(c("alpha", "beta", "gamma", "lambda"), size = 150, replace = TRUE, prob = c(0.3, 0.5, 0.1, 0.1)))
   , group = rep(c("T", "C"), 75)
 )

fq <- dt[, .(count = .N), by = .(col1, col2, col3, group)]

ggplot(as.data.frame(fq),
       aes(y = count
         , axis1 = col1
         , axis2 = col2
         , axis3 = col3
         )) +
    geom_alluvium(aes(fill = group), width=1/3) +
    geom_stratum(width = 1/6) +
    geom_text(stat = "stratum", aes(label = after_stat(stratum))) + 
    ## geom_label_repel(stat = "stratum", infer.label = TRUE, label.strata=TRUE) +
    scale_x_discrete(limits = c("Col 1", "Col 2"
                              , "Col 3"
                                )
                   , expand = c(.0, .0)) +
    ## theme_bw() +
    theme(panel.grid.major = element_blank()
        , panel.grid.minor = element_blank()
        , panel.background = element_blank()
        , panel.border = element_blank())


```


# geom_flow

```{r}

ggplot(data = fq 
     , aes(
           y = count
         , axis1 = col1
         , axis2 = col2
         , axis3 = col3
       )) +
    geom_flow(
        aes(fill = group), stat = "alluvium"
      , lode.guidance = "rightleft"
      , color = "white"
      , na.rm = TRUE
    ) +
    scale_x_discrete(limits = c("col1", "col2", "col3")) + 
    geom_stratum(alpha = .5, na.rm = TRUE, color = "grey") +
    geom_text(stat = "stratum", size = 3, aes(label = after_stat(stratum))) +
    ggtitle("") + 
    xlab("") + 
    theme_minimal()
## theme(legend.position = "none")

```



# R sessionInfo

```{r}
sessionInfo()

```
