---
title: "Descritization"
author: "Wu Gong"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: false
    code_folding: hide
    toc_depth: 6
    lightbox: true
    gallery: false
    highlight: monochrome
    css: Wu.css
---



```{r setup, echo=FALSE, cache=FALSE,warning=FALSE,message=FALSE}
library(knitr)
library(rmdformats)
library(Wu)
opts_chunk$set(echo=TRUE,
               cache=FALSE,
               eval=TRUE,
               prompt=FALSE,
               results="asis",
               tidy=FALSE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               out.width = '80%')
eval_fast <- TRUE
eval_slow <- FALSE
```



# [Index](index.html)


# "discretization" package

 * FSelectorRcpp: 'Rcpp' Implementation of 'FSelector' Entropy-Based Feature
Selection Algorithms with a Sparse Matrix Support

```{r}

library(FSelectorRcpp)


t <- discretize(x = iris[[1]], y = iris[[5]])
setDT(t)

colnames(t) %>% prt()

dt <- as.data.table(iris)
colnames(dt) %>% prt()

dt2 <- discretize(x = dt$Sepal.Length, y = dt$Species, all = TRUE)
colnames(dt2) %>% prt()

setDT(dt2)
dt2[,.N,by=.(Species, Sepal.Length)][order(Species, Sepal.Length)] %>% prt()



```


```{r}
library(FSelector)
data(iris)

weights <- information.gain(Species~., iris)
print(weights)

subset <- cutoff.k(weights, 2)

f <- as.simple.formula(subset, "Species")
print(f)


```


# Discretize Continuous Variables based on the Outcome


```{r}

library(FSelectorRcpp)

set.seed(123456)
n <- 300
dt <- data.table(x = rnorm(n), noise = rnorm(n))
dt <- dt[, outcome := x ^ 2 + noise / 5]

discretization <- function(data, predictor, outcome, num = 5){
  data <- data[!is.na(data[[predictor]])]
  predictor_discretized <- paste0(predictor, "_discretized")
  x <- data[[predictor]]
  y <- data[[outcome]]
  data[[predictor_discretized]] <- FSelectorRcpp::discretize(x, y
                                                           , all = TRUE
                                                           , control = list(equalsizeControl(num)))[, 2]
  invisible(data)
}

dt2 <- discretization(data = dt, predictor = "x", outcome = "outcome", num = 5)


crrs <- Wu::Table2_nbyc(data = dt2
                      , group = c("x_discretized")
                      , var = "outcome"
                      , digits_c = 3, digits_p = 4)

crrs %>% prt()

```

