---
title: "R Notes"
author: "Wu Gong"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: false
    code_folding: hide
    toc_depth: 6
    lightbox: true
    gallery: false
    highlight: monochrome
    css: Wu.css
---




```{r setup, echo=FALSE, cache=FALSE,warning=FALSE,message=FALSE}
library(knitr)
library(rmdformats)
library(Wu)
opts_chunk$set(echo=TRUE,
               cache=FALSE,
               eval=TRUE,
               cache=FALSE,
               prompt=FALSE,
               results="asis",
               tidy=FALSE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               out.width = '80%')
eval_fast <- TRUE
eval_slow <- FALSE
```






# Visualization
 * [R Graphics](graph.html)
 * [Flow Chart](flowchart.html)
 * [Map: Hydraulic Dams around the World](hydraulic_dams_around_the_world.html)
 * [Map: highcharter](map_highcharter.html)
 * [Social Network with Gephi](network_Gephi.html)
 * [Hierarchical Newtork with visNetwork](network_visNetwork.html)
 * [Collapsible Tree](collapsible_tree.html)
 * [Heatmaps for Correlation Matrix](heatmap_correlation.html)
 * [Spaghetti Plot](spaghetti_plot.html)
 * [Alluvium Plot](alluvium.html)
 * [Rolling Average](rolling_average.html)
 * [Contour Plot](contour_plot.html)
 * [Word Cloud](word_cloud.html)
 * [plotly Symbols](plotly_symbols.html)
 * [plotly Scatter Plot](plotly_scatterplot.html)
 * [RMarkdown Slides](rmarkdown_slides.html)


# Modeling


 * [LASSO: Least Absolute Shrinkage and Selection Operation](lasso.html)
 * [CART: Classification And Regression Trees](cart.html)
 * [Random Forest with R & Python](randomforest.html)
 * [Regression Method](regression.html)
 * [Cluster Analysis](clustering.html)
 * [Multi-State Process](multi_state.html)
 * [SHAP: SHapley Additive exPlanations](shap.html)
 * [Support Vector Machine (SVM)](support_vector_machine.html)
 * [Time to Event](time_to_event.html)
 * [Mediation Analysis](mediation_analysis.html)

# Data Wrangling
 * [Data Manipulation](data_manipulation.html)
 * [Data Description](data_description.html)
 * [R Notes](r_notes.html)
 * [Discretization](discretization.html)

# Statistics
 * [Power and Sample Size Simulation for Two Proportions](simulation_proportion.html)
 * [Power Analysis: Non-inferiority Cluster Randomised Trial](power_analysis.html)
 * [Restricted Cubic Spline](restricted_cubic_spline.html)
 * [Jeffreys Interval for One-Sample Proportion with SAS/STAT® Software](https://support.sas.com/resources/papers/proceedings15/3020-2015.pdf)


# R Programming
 * [Intall R Packages](install_packages.html)
 * [R Markdown HTML Output Style](style.html) 
 * [flexdashboard Template](template_flexdashboard.html)
 * [Notebook Template](template_notebook.html)
 * [R Markdown with Tabs](rmarkdown_with_tabs.html)
 * [R6 Object](R6.html) 

# [Python](python.html)

 * [Run Python within rmarkdown](python.html)
