---
title: "Missing Values"
author: "Wu Gong"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: false
    code_folding: hide
    toc_depth: 6
    lightbox: true
    gallery: false
    highlight: monochrome
    css: Wu.css
---


	
```{r setup, echo=FALSE, cache=FALSE,warning=FALSE,message=FALSE}
library(knitr)
library(rmdformats)
library(Wu)
opts_chunk$set(echo=TRUE
             , cache=FALSE
             , eval=TRUE
             , prompt=FALSE
             , results="asis"
             , tidy=FALSE
             , comment=NA
             , message=FALSE
             , warning=FALSE
             , out.width = '80%'
             , class.source='klippy'
               )
eval_fast <- TRUE
eval_slow <- FALSE
klippy::klippy(position = c('top', 'left')
             , tooltip_message = 'Click to copy'
             , tooltip_success = 'Done')
```




# [Back to Index](index.html)


# Scale

 * Normalize data

```{r}
x <- c(1, 3, 4, NA, 9, 11, 5, 2, 3, 4)
y <- c(2, 5, 3, 5, NA, 0, NA, 2, 3, 9)
dt <- data.table(x, y)

sdt <- scale(dt)

sdt %>% prt()


dt2 <- cbind(dt, sdt)
colnames(dt2) <- c("x", "y", "x_scaled", "y_scaled")

dt2 %>% prt() %>%
    add_footnote(paste0("Center: ", paste0(attr(sdt, "scaled:center"), collapse = ", "), "\n"
                      , "Scale: ", paste0(attr(sdt, "scaled:scale"), collapse = ", ")))

```


# Single Impute Continuous Variables

 * Add a variable flagging if it is missing (indicator of imputed values)

```{r}
add_isna <- function(x) {
  invisible(factor(ifelse(is.na(x), 0, 1), levels = c(0, 1)))
}


missing_indicator <- function(data, name){
  name_imputed <- paste0(name, "_imputed")
  name_is_impuated <- paste0(name, "_is_impuated")
  data[[name_imputed]] <- Wu::single_impute(data[[name]])
  data[[name_is_impuated]] <- factor(is.na(data[[name]]), levels = c(FALSE, TRUE), labels = c(0, 1))
  invisible(data)
}


dt3 <- missing_indicator(dt, "x")

imp_median <- function(x){
  y <- x
  ## y[is.na(y)] <- mean(x, na.rm = TRUE)
  y[is.na(y)] <- median(x, na.rm = TRUE)
  invisible(y)
}


dt3 %>% prt()

```

# Add Missing Indicator to Categorical Variables

```{r}

dt <- data.table(var1 = factor(sample(c("A", "B", as.character(NA)), size = 20, replace = TRUE), levels = c("A", "B")))

addno <- function(x, na_ind = "Not Obtained"){
  y <- factor(ifelse(is.na(x), na_ind, as.character(x)), levels = c(levels(x), na_ind))
}


dt <- dt[, var1_addno := addno(var1)]

dt %>% prt()

```

# Model Matrix

## Create Model Matrix

```{r}
n <- 10
dt <- data.table(var1 = rnorm(n)
               , var2 = rnorm(n)
               , var3 = sample(c("A", "B", "C"), size = n, replace = TRUE))

Predictors <- c("var1", "var2", "var3")
frml <- Wu::wu_formula(outcome = "", predictors = Predictors)
mmx <- model.matrix.lm(frml, data = dt, na.action = "na.pass")

mmx %>% prt()
```

## Splitting

```{r}
set.seed(123456)
seq1 <- sample(c("Train", "Test"), size = nrow(dt), replace = TRUE, prob = c(0.8, 0.2))

```

# Multiple Imputation


```{r}
x <- c(1, 3, 4, NA, 9, 11, 5, 2, 3, 4)
y <- c(2, 5, 3, 5, NA, 0, NA, 2, 3, 9)
dt <- data.table(x, y, noise1 = rnorm(10), noise2 = rnorm(10))
dt <- dt[, x2 := x * (2 + noise1 / 5)
         ][, y2 := y * 2 + noise2 / 3]

library(mice)
set.seed(123456)
dt_im <- mice(dt, m = 2, method = "pmm")
dm <- complete(dt_im, "long")

dm %>% prt()
```

# R sessionInfo

```{r}
sessionInfo()

```
