---
title: "Oridnal Regression"
author: "Wu Gong"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: false
    code_folding: hide
    toc_depth: 6
    lightbox: true
    gallery: false
    highlight: monochrome
    css: Wu.css
---



```{r setup, echo=FALSE, cache=FALSE,warning=FALSE,message=FALSE}
library(Wu)
library(rmdformats)
opts_chunk$set(echo=FALSE,
               eval=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=FALSE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               out.width = '80%')
eval_fast <- TRUE
eval_slow <- FALSE
```


# Index

[Index](index.html)


# Reference

# Data

* American Community Survey (ACS) data of Nashville, TN, 2018
* Data Dictionary: https://www2.census.gov/programs-surveys/acs/tech_docs/pums/data_dict/PUMS_Data_Dictionary_2014-2018.pdf


```{r}

## data(package = "Wu")
library(Wu)
dt <- acs2018_nashville

## hist(dt$agep)

## dt[, .N, by = .(schl)][order(schl)]

dt <- dt[, education_level3 := case_when(
               is.na(as.numeric(schl)) ~ "High School or Less"
             , as.numeric(schl) <= 17 ~ "High School or Less"
             , as.numeric(schl) <= 21 ~ "Undergraduate or Less"
             , TRUE ~ "Graduate")
         ][, education_level3 := factor(education_level3
                                      , levels = c("High School or Less"
                                                 , "Undergraduate or Less"
                                                 , "Graduate")
                                        , ordered = TRUE)
           ][, gender := case_when(
                   sex %in% 1 ~ "Male"
                 , sex %in% 2 ~ "Female"
                 , TRUE ~ as.character(NA))
             ][, gender := factor(gender, levels=c("Male", "Female"))
               ][, wagp_log := log(wagp)]
dt[, .N, by = .(education_level3)][order(education_level3)] %>% prt()


## hist(dt$wagp)
## summary(dt$wagp)
dt <- dt[!is.na(wagp) & wagp > 0 & !is.na(wagp_log)]
## hist(dt$wagp_log)
```

# Plot

```{r}
gt_cdf <- function (data, ordinal, group){
    rtn <- data[, .(n = .N), by = setNames(list(get(ordinal), get(group)), c(ordinal, group))
                ][order(get(ordinal), get(group))
                  ][, `:=`(df, n/sum(n)), by = list(get(group))
                    ][, `:=`(cdf, cumsum(df)), by = list(get(group))
                      ][, `:=`(lcdf,  qlogis(cdf))
                        ][cdf < 1
                          ][order(get(ordinal), get(group))]
    tw <- copy(rtn)[1:2, ]
    tw[[ordinal]] <- 0
    ## [, get(ordinal) := 0]
    ## [, `:=`(get(ordinal), 0)]
    ## rtn <- rbind(tw, rtn)
    rtn[[paste0(ordinal, "_n")]] <- as.numeric(rtn[[ordinal]])
    return(rtn)
}


dt <- dt[, education_n := as.numeric(education_level3)]
cdf <- gt_cdf(dt, ordinal = "education_n", group="gender")

gg_cdf <- function (data, ordinal, group) {
    cdf <- gt_cdf(data = data, ordinal = ordinal, group = group)
    ## cdf <- cdf[, `:=`(size, n/max(n))][, size := 1]
    brks <- c(0.1, 0.5, 0.8, 0.9, 0.95, 0.98)
    lbrks <- qlogis(brks)
    group_label <- ifelse(label(data[[group]]) %in% c(""), group, 
                          label(data[[group]]))
    p <- ggplot(data = cdf
              , aes_string(x = ordinal
                         , y = "lcdf"
                         , group = group
                         , color = group
                         ## , alpha = "size"
                           )) +
        geom_step(size=1, direction = "mid") +
        theme_bw() +
        theme(panel.grid.major = element_blank()
            , panel.grid.minor = element_blank()
            , legend.position = c(0.99, 0.4)
            , legend.justification = c("right", "top")
            , legend.title=element_text(size=15)
            , legend.text=element_text(size=10)
              ) + 
        guides(alpha = FALSE) +
        scale_x_continuous(breaks=1:9, labels=1:9, limits = c(0.5, 9.5)) +
        scale_y_continuous(breaks=lbrks, labels = scales::percent(brks, 1), limits = qlogis(c(0.05, 0.99))) + 
        labs(y = "", x = "", color = group_label)
    return(p)
}

label(dt$gender) <- "Gender"
gg_cdf(dt, ordinal = "education_n", group="gender")


```

# Plot using rmsb


```{r}
library(rmsb)
x <- as.numeric(dt$education_level3)
y <- factor(dt$gender)

Ecdf( ~ x, group = y, fun = qlogis, ylab = "Logit of Proportions of Values < X")

```


# Ordinal with MASS package

```{r}
library(MASS)
m <- polr(education_level3 ~ gender + wagp_log
        , data = dt
        , Hess = TRUE)

library(sjPlot)


```

# ordinal package


```{r}
library(ordinal)
m_ordinal <- clm(education_level3 ~ gender + wagp_log
        , data = dt
        , link = "logit")

tab_model(m_ordinal)

```

# rms package

```{r}
library(rms)
dd <- datadist(dt); options(datadist='dd')
m_lrm <- lrm(education_level3 ~ gender + wagp_log
        , data = dt
          )


summary(m_lrm)


```

# glm package

* Re-code education level into three variables


```{r}
dt <- dt[, education_ge_undergraduate := as.numeric(education_level3 %in% c("Undergraduate or Less", "Graduate"))
         ][, education_ge_graduate := as.numeric(education_level3 %in% c("Graduate"))]

dt1 <- copy(dt)[, y := 1-education_ge_undergraduate
                ][, lvl1 := 1
                  ]

dt2 <- copy(dt)[][, y := 1-education_ge_graduate
          ][, lvl1 := 0]
dtb <- rbind(dt1, dt2)

dtb[, .N, by = .(lvl1)]
dtb[, .N, by = .(y)]

m_glm <- glm(y ~ 0 + factor(lvl1) + gender + wagp_log
           , data=dtb
           , family = binomial
             , epsilon=1e-19
           ## , glm.control(epsilon = 1e-8, maxit = 25, trace = FALSE)
             )
summary(m_glm)

library(rms)
dd <- datadist(dtb); options(datadist='dd')
m_lrm <- lrm(y ~ lvl1 + gender + wagp_log
           , data=dtb
          )
coef(m_lrm)
summary(m_lrm)
coef(m_lrm)


m_glm <- glm(y ~ lvl1 + gender + wagp_log
           , data=dtb
           , family = binomial
             )
summary(m_glm)

m_glm <- glm(y ~ gender + wagp_log + education_ge_undergraduate + education_ge_graduate
           , data=dtb
           , family = binomial
             )

summary(m_glm)

```


# brms package

```{r}
library(brms)

m_brm <- brm(education_level3 ~ gender + wagp_log
, data=dt
, family = cumulative(link = "logit", threshold = "flexible")
  )
summary(m_brm)

m_brm_recoded <- brm(y ~ lvl1 + gender + wagp_log
           , data=dtb
           , family = binomial
             )
summary(m_brm_recoded)


```
