---
title: "NCI SDTM Terminology"
author: "Wu Gong"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: false
    code_folding: hide
    toc_depth: 6
    lightbox: true
    gallery: false
    highlight: monochrome
    css: Wu.css
---


	
```{r setup, echo=FALSE, cache=FALSE,warning=FALSE,message=FALSE}
library(knitr)
library(rmdformats)
library(Wu)
opts_chunk$set(echo=TRUE
             , cache=FALSE
             , eval=TRUE
             , prompt=FALSE
             , results="asis"
             , tidy=FALSE
             , comment=NA
             , message=FALSE
             , warning=FALSE
             , out.width = '80%'
             , class.source='klippy'
               )
eval_fast <- TRUE
eval_slow <- FALSE
klippy::klippy(position = c('top', 'left')
             , tooltip_message = 'Click to copy'
             , tooltip_success = 'Done')
```




# [Back to Index](index.html)



# Data

 * [SDTM NCI Terminology](https://datascience.cancer.gov/resources/cancer-vocabulary/cdisc-terminology)

```{r}
dt <- read.delim(file = "https://evs.nci.nih.gov/ftp1/CDISC/SDTM/SDTM%20Terminology.txt"
               , header = TRUE, sep = "\t", dec = "\t")

DT::datatable(data = dt
            , filter = "top"
            , rownames = FALSE
            , extensions = "Buttons"
            , options = list(dom = "Bfrtip"
                           , buttons = I("colvis")
                           , pageLength = 20
                             ))

```




